kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kratix-gitea
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-type: platform
  template:
    metadata:
      name: kratix-gitea
      namespace: argocd
    spec:
      destination:
        namespace: gitea
        server: https://kubernetes.default.svc
      project: core-services
      source:
        path: gitops-repo/kratix-gitea
        repoURL: https://github.com/abangser/platform-demo.git
      syncPolicy:
        automated:
          prune: true
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
