kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kratix-worker
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-type: worker
  template:
    metadata:
      name: kratix-worker
      namespace: argocd
    spec:
      destination:
        namespace: kratix-worker-system
        server: https://kubernetes.default.svc
      project: core-services
      source:
        path: "gitops-repo/kratix-worker"
        repoURL: https://github.com/abangser/platform-demo.git
      syncPolicy:
        automated: {}
        syncOptions: # Sync options which modifies sync behavior
          - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
